name: python-deployment
run-name: ${{github.actor}} - ${{github.ref_name}}

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{env.PYTHON_VERSION}}
        with:
          python-version: '${{env.PYTHON_VERSION}}'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 pytest

      - name: Lint code with flake8
        run: |
          cd ../
          flake8 . --show-source --statistics --exit-zero

      - name: Check code complexity with flake8
        continue-on-error: true
        run: flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Test with python
        run: |
          pytest

      - name: Generate coverage report
        run: pytest --cov-report=xml --cov=.

      - name: Test coverage
        run: pytest  -v --cov-report=term-missing --cov=.

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
          with:
            name: python-artifacts
            path: .

